services:
  ticketfair-app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - ticketfair-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/public/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      APP_PORT: 8000
      DB_HOST: ticketfair-db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: ticketfair_db
    depends_on:
      - ticketfair-db

  ticketfair-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ticketfair_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ticketfair_db-data:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - ticketfair-network

networks:
  ticketfair-network:
    driver: bridge

volumes:
  ticketfair_db-data:
    driver: local
