basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the home page.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Show the home page.
      tags:
      - Home
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of the server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of the server.
      tags:
      - Health
  /not-found:
    get:
      consumes:
      - '*/*'
      description: Returns a 404 error for not found routes.
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Handle not found routes.
      tags:
      - NotFound
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
