basePath: /
definitions:
  models.Event:
    properties:
      date:
        type: string
      description:
        type: string
      event_id:
        type: string
      location:
        type: string
      merchant_id:
        type: string
      name:
        type: string
    required:
    - date
    - description
    - location
    - merchant_id
    - name
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  models.Merchant:
    properties:
      description:
        type: string
      merchant_id:
        type: string
      name:
        type: string
    type: object
  models.MerchantRep:
    properties:
      email:
        type: string
      id:
        type: string
      merchant_id:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  models.Profile:
    properties:
      address:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
      profile_id:
        type: string
      user_id:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      password:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /merchant/events/new/event:
    post:
      consumes:
      - application/json
      description: Create a new event with the provided details.
      parameters:
      - description: Event data
        in: body
        name: event
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            items:
              type: string
            type: array
      summary: Create a new event.
      tags:
      - Events
  /merchant/new/rep:
    post:
      consumes:
      - application/json
      description: Create a new merchant representative with the provided details.
      parameters:
      - description: Merchant Representative data
        in: body
        name: merchantRep
        required: true
        schema:
          $ref: '#/definitions/models.MerchantRep'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.MerchantRep'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new merchant representative.
      tags:
      - Merchant Representatives
  /merchants/new/merchant:
    post:
      consumes:
      - application/json
      description: Create a new merchant
      parameters:
      - description: Merchant
        in: body
        name: merchant
        required: true
        schema:
          $ref: '#/definitions/models.Merchant'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Merchant'
        "400":
          description: Bad Request
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              type: string
            type: array
      summary: Create a new merchant
      tags:
      - merchants
  /not-found:
    get:
      consumes:
      - '*/*'
      description: Returns a 404 error for not found routes.
      produces:
      - application/json
      responses:
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Handle not found routes.
      tags:
      - NotFound
  /private/profile/new:
    post:
      consumes:
      - application/json
      description: Create a new profile with user ID and other details.
      parameters:
      - description: Profile data
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/models.Profile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new profile.
      tags:
      - Profiles
  /private/profile/update:
    post:
      consumes:
      - application/json
      description: Update an existing profile with new details.
      parameters:
      - description: Profile data
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/models.Profile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update an existing profile.
      tags:
      - Profiles
  /private/users:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all users.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Profile'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all users.
      tags:
      - Profiles
  /private/users/:id:
    get:
      consumes:
      - application/json
      description: Retrieve a user by their ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a user by ID.
      tags:
      - Profiles
  /private/users/me:
    get:
      consumes:
      - application/json
      description: Retrieve the details of the currently authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get the currently authenticated user.
      tags:
      - Profiles
  /public/:
    get:
      consumes:
      - '*/*'
      description: get the home page.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Show the home page.
      tags:
      - Home
  /public/auth/client/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user with email and password
      parameters:
      - description: Login request data
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Authenticate a user.
      tags:
      - Auth
  /public/auth/logout:
    post:
      consumes:
      - application/json
      description: Logout a user by clearing the Authorization
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Logout a user.
      tags:
      - Auth
  /public/health:
    get:
      consumes:
      - '*/*'
      description: get the status of the server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of the server.
      tags:
      - Health
  /public/newuser:
    post:
      consumes:
      - application/json
      description: Create a new user with email, password, and username.
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new user.
      tags:
      - Users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
